# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170722_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
