# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170722_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='occupational_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.OccupationalCategory'),
        ),
    ]
