# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170722_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedKeywords',
            new_name='RelatedKeyword',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
