# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20170726_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='career_ladder',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='exam_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
